### ISSUE TITLE
When a PR is open the golangci-lint job is running twice

### ISSUE THREAD

**Issue by whutchinson98** [rog-golang-buddies/golang-template-repository#59]
![image](https://user-images.githubusercontent.com/6412775/179241637-6e976236-cd5a-4638-ae8b-c7242ab5fb96.png)

Proposal for fix:
Only have the job run on `pull_request` into branch `main` as it doesn't really matter if the lint fails until it is trying to be merged into `main`

**Comment by haani-niyaz** [comment]
@whutchinson98 this was planned to be addressed in #46. Although it sets the job to run on `push` only for gitleaks, tests and linting. 

My rationale for this was to get early feedback instead of discovering the potentially sizeable refactoring effort needed if left until the end. For instance, when the linter runs (if setup with valid options) it might pick up on a patterns that are discouraged. Having this feedback early will aid the developer to fix-on-fail instead of perhaps propagating the anti-pattern in multiple places and then having to fix a larger a codebase. 

I'm also aware that this may get picked up locally via the `pre-commit` hook but it relies on the developer installing the hook so it not a guarantee.
